### ISSUE TITLE
Add support for Symfony 3.0

### ISSUE THREAD

**Issue by robholmes** [arodiss/XlsBundle#16]
Currently the `composer.json` requires `"symfony/framework-bundle": "~2.3"`, it seems that everyone else is adding this `|~3.0` to their requirements, resulting in: `"symfony/framework-bundle": "~2.3|~3.0"`

**Comment by arodiss** [comment]
Thank you @robholmes 
I checked briefly and looks like indeed bundle does not rely on anything deprecated, so I merged your PR

**Comment by robholmes** [comment]
Thanks @arodiss
