### ISSUE TITLE
error in Readme

### ISSUE THREAD

**Issue by yaboroda** [arodiss/XlsBundle#25]
Return XLS file from Symfony controller

$file = $container
    ->get("arodiss.xls.builder")
    ->createAndWrite(array(
        array("row one field one", "row one field two"),
        array("row two field one")
    ))
;

But there is no method createAndWrite() in XlsBuilder class. There is buildXlsFromArray() method.

PS thanks for you bundle. It simple to use and it works. Perfect for my project.

**Comment by arodiss** [comment]
Thank you for notice.
README updated.
